#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p '' -font 'Iosevka Nerd Font 9' -width 10 -lines 4 -location 2 -yoffset 62 <<< "Lock|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -s;;
                *Logout) bspc quit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
